### 신규 주문
POST http://localhost:8080/v1/orders/new
Content-Type: application/json

{
  "orderer": {
    "name": "해피쿠",
    "phoneNumber": "010-5678-1234"
  },
  "newlyOrderedItem": [
    {
      "itemIdx": 1,
      "productId": "b1c2d3e4-f567-8901-2345-6789abcdef02",
      "productName": "농심 짜파게티 4봉",
      "price": 4500,
      "quantity": 2,
      "amounts": 9000
    },
    {
      "itemIdx": 2,
      "productId": "0f1e2d3c-4b5a-6978-9012-3456789abcdf",
      "productName": "콜라 500ml",
      "price": 1800,
      "quantity": 1,
      "amounts": 1800
    }
  ]
}

### 토스 결제 테스트
POST https://api.tosspayments.com/v1/payments/confirm
Authorization: Basic dGVzdF9nc2tfZG9jc19PYVB6OEw1S2RtUVhrelJ6M3k0N0JNdzY6
Content-Type: application/json

{
  "paymentKey": "tgen_20251222161807BTGi2",
  "paymentType": "",
  "orderId": "d4782f4b-8dac-4da3-8a78-1e70f6dbbf17",
  "amount": 1500

}

### 결제 테스트
GET http://localhost:8080/payment/checkout.html?orderId=22938d41-0fec-4a9c-befa-14d68f8803827&userId=rudals4549&ordererName=해피쿠&ordererPhoneNumber=01012341234&orderName=사리곰탕&amount=1500


### 결제 취소 테스트

POST http://localhost:8080/v1/payment/cancel
Content-Type: application/json

{
  "orderId": "5facb1b7-2bd2-4de7-a748-82b6802cbf49",
  "cancelReason": "단순 변심",
  "cancellationAmount": 1500
}
